<?php
require_once("response_xml.php");

function handle_steam_ticket($x,$AuthTicket,$ClientVersion)
{
	$resp = new Response("LoginResponse");

	//TODO: Implement database of some sort
	//Hook AuthTicket on the client side to generate our own authentication token of some sort
	//Could also possibly update $x to contain a token generated by us...

	$res = $resp->add_result();
	$res->add_attribute("UserId",123456);
	$res->add_attribute("AccountId",123457);
	$resp->run();
}


?>